<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="date" content="2016-01-27" />

<title>Machine Learning Course Project</title>

<script src="index_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="index_files/bootstrap-3.3.1/css/bootstrap.min.css" rel="stylesheet" />
<script src="index_files/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="index_files/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="index_files/bootstrap-3.3.1/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="index_files/highlight/default.css"
      type="text/css" />
<script src="index_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img { 
  max-width:100%; 
  height: auto; 
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">Machine Learning Course Project</h1>
<h4 class="date"><em>January 27, 2016</em></h4>
</div>


<div id="background" class="section level2">
<h2>Background</h2>
<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: <a href="http://groupware.les.inf.puc-rio.br/har" class="uri">http://groupware.les.inf.puc-rio.br/har</a> (see the section on the Weight Lifting Exercise Dataset).</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>The training data for this project are available here:</p>
<p><a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv" class="uri">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv</a></p>
<p>The test data are available here:</p>
<p><a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv" class="uri">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv</a> For ease of processing files and simplification of code, download the csv files and save to the set working directory, MachineLearning on the desktop.</p>
<pre class="r"><code>setwd(&quot;~/Desktop/coursera/MachineLearning&quot;)</code></pre>
<pre class="r"><code>## Load the preferred libraries 
library(caret) </code></pre>
<pre><code>## Warning: package &#39;caret&#39; was built under R version 3.2.3</code></pre>
<pre><code>## Loading required package: lattice
## Loading required package: ggplot2</code></pre>
<pre class="r"><code>library(rpart)
library(randomForest)</code></pre>
<pre><code>## randomForest 4.6-12
## Type rfNews() to see new features/changes/bug fixes.</code></pre>
<pre class="r"><code>library(AppliedPredictiveModeling)</code></pre>
<p>Two sets of data were provided, training and test.</p>
<p>The Test set contains the exercise readings for 20 participants without the “classe” variable of exercise provided. We will attempt to determine this “classe” with the use of predictive modelling, built using the training set. We will set the Test set to the side until the models are completed.</p>
<p>With the following code, we’ll read the data.</p>
<pre class="r"><code>pmlTrain &lt;- read.csv(&quot;pml-training.csv&quot;, header=TRUE, na.strings=c(&quot;NA&quot;,&quot;#Div/0!&quot;))  ## The training set
pmlTest &lt;- read.csv(&quot;pml-testing.csv&quot;, header=TRUE, na.string=c(&quot;NA&quot;, &quot;#Div/0!&quot;)) ## The test set -set aside
dim(pmlTrain)</code></pre>
<pre><code>## [1] 19622   160</code></pre>
<pre class="r"><code>dim(pmlTest)</code></pre>
<pre><code>## [1]  20 160</code></pre>
<pre class="r"><code>summary(pmlTrain$classe)</code></pre>
<pre><code>##    A    B    C    D    E 
## 5580 3797 3422 3216 3607</code></pre>
<p>There are 19622 records with 159 variables (the first column is just a numeric count of observations). The “classe” variable we are solving for is divided among 5 classes.</p>
<div id="cleaning-the-data" class="section level3">
<h3>Cleaning the data</h3>
<p>We’ll clean out the <a href=http://www.inside-r.org/packages/cran/caret/docs/nearZeroVar>NearZeroVariance</a> variables and remove them from our data, and remove the first column, a count of the observations.</p>
<pre class="r"><code>nzv &lt;- nearZeroVar(pmlTrain, saveMetrics=TRUE)  ## remove nearZeroVariances
pmlTrain &lt;- pmlTrain[,nzv$nzv==FALSE]
pmlTrain &lt;- pmlTrain[c(-1)]  ## remove first column (count)</code></pre>
<p>Remove observations with 75% NA:</p>
<pre class="r"><code>noNAs&lt;- pmlTrain ## find and remove 75% of NAs
for(i in 1:length(pmlTrain)) {
    if( sum( is.na( pmlTrain[, i] ) ) /nrow(pmlTrain) &gt;= 0.75) {
        for(j in 1:length(noNAs)) {
            if( length( grep(names(pmlTrain[i]), names(noNAs)[j]) ) == 1)  {
                noNAs &lt;- noNAs[ , -j]
            }   
        } 
    }
}
pmlTrain &lt;- noNAs ## set back to name
rm(noNAs) ## remove excess data
dim(pmlTrain)</code></pre>
<pre><code>## [1] 19622    58</code></pre>
<p>This brings us down to 58 columns.</p>
</div>
<div id="split-data" class="section level3">
<h3>Split data</h3>
<p>Now we’ll split the data into a 60/40 training/test set to train the model then test the model before using for our prediction on the 20 observations in the final set.</p>
<pre class="r"><code>inTrain &lt;- createDataPartition(y=pmlTrain$classe,p=.60,list=FALSE)
train &lt;-pmlTrain[inTrain,]
test &lt;- pmlTrain[-inTrain,]</code></pre>
<pre class="r"><code>dim(train)</code></pre>
<pre><code>## [1] 11776    58</code></pre>
<pre class="r"><code>dim(test)</code></pre>
<pre><code>## [1] 7846   58</code></pre>
</div>
<div id="prediction-with-random-forests" class="section level3">
<h3>Prediction with Random Forests</h3>
<p>For <a href=http://www.statmethods.net/advstats/cart.html>Random Forest information</a></p>
<pre class="r"><code>set.seed(4726)
modelFitA1 &lt;- randomForest(classe ~ ., data=train)
predictionA1 &lt;- predict(modelFitA1, test, type = &quot;class&quot;)
modelRF &lt;- confusionMatrix(predictionA1, test$classe)
modelRF</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2232    1    0    0    0
##          B    0 1517    3    0    0
##          C    0    0 1365    2    0
##          D    0    0    0 1284    0
##          E    0    0    0    0 1442
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9992          
##                  95% CI : (0.9983, 0.9997)
##     No Information Rate : 0.2845          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.999           
##  Mcnemar&#39;s Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            1.0000   0.9993   0.9978   0.9984   1.0000
## Specificity            0.9998   0.9995   0.9997   1.0000   1.0000
## Pos Pred Value         0.9996   0.9980   0.9985   1.0000   1.0000
## Neg Pred Value         1.0000   0.9998   0.9995   0.9997   1.0000
## Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
## Detection Rate         0.2845   0.1933   0.1740   0.1637   0.1838
## Detection Prevalence   0.2846   0.1937   0.1742   0.1637   0.1838
## Balanced Accuracy      0.9999   0.9994   0.9987   0.9992   1.0000</code></pre>
<pre class="r"><code>plot(modelFitA1)</code></pre>
<p><img src="index_files/figure-html/randomForest-1.png" /></p>
<pre class="r"><code>importance(modelFitA1)</code></pre>
<pre><code>##                      MeanDecreaseGini
## user_name                    89.77920
## raw_timestamp_part_1        953.77048
## raw_timestamp_part_2         10.72094
## cvtd_timestamp             1430.59179
## num_window                  538.66808
## roll_belt                   523.70417
## pitch_belt                  301.98972
## yaw_belt                    351.15694
## total_accel_belt            111.99706
## gyros_belt_x                 36.92476
## gyros_belt_y                 52.32103
## gyros_belt_z                113.29464
## accel_belt_x                 64.46205
## accel_belt_y                 65.38756
## accel_belt_z                200.47035
## magnet_belt_x               111.92927
## magnet_belt_y               197.78657
## magnet_belt_z               188.14990
## roll_arm                    119.77482
## pitch_arm                    55.33093
## yaw_arm                      82.13894
## total_accel_arm              29.01066
## gyros_arm_x                  42.41750
## gyros_arm_y                  41.80405
## gyros_arm_z                  18.06497
## accel_arm_x                  84.11830
## accel_arm_y                  54.05321
## accel_arm_z                  39.32734
## magnet_arm_x                 84.38316
## magnet_arm_y                 71.14505
## magnet_arm_z                 52.26065
## roll_dumbbell               189.65772
## pitch_dumbbell               83.99346
## yaw_dumbbell                112.99471
## total_accel_dumbbell        117.74722
## gyros_dumbbell_x             40.69216
## gyros_dumbbell_y            107.88070
## gyros_dumbbell_z             22.68877
## accel_dumbbell_x            133.68755
## accel_dumbbell_y            187.83419
## accel_dumbbell_z            133.96881
## magnet_dumbbell_x           221.40833
## magnet_dumbbell_y           310.57406
## magnet_dumbbell_z           304.41019
## roll_forearm                250.93362
## pitch_forearm               299.34184
## yaw_forearm                  48.79677
## total_accel_forearm          29.46125
## gyros_forearm_x              26.18619
## gyros_forearm_y              40.88536
## gyros_forearm_z              26.54757
## accel_forearm_x             130.86616
## accel_forearm_y              43.08441
## accel_forearm_z              90.79598
## magnet_forearm_x             70.05236
## magnet_forearm_y             75.82485
## magnet_forearm_z             93.14230</code></pre>
<pre class="r"><code>print(modelRF)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2232    1    0    0    0
##          B    0 1517    3    0    0
##          C    0    0 1365    2    0
##          D    0    0    0 1284    0
##          E    0    0    0    0 1442
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9992          
##                  95% CI : (0.9983, 0.9997)
##     No Information Rate : 0.2845          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.999           
##  Mcnemar&#39;s Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            1.0000   0.9993   0.9978   0.9984   1.0000
## Specificity            0.9998   0.9995   0.9997   1.0000   1.0000
## Pos Pred Value         0.9996   0.9980   0.9985   1.0000   1.0000
## Neg Pred Value         1.0000   0.9998   0.9995   0.9997   1.0000
## Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
## Detection Rate         0.2845   0.1933   0.1740   0.1637   0.1838
## Detection Prevalence   0.2846   0.1937   0.1742   0.1637   0.1838
## Balanced Accuracy      0.9999   0.9994   0.9987   0.9992   1.0000</code></pre>
</div>
<div id="prediction-with-decision-trees" class="section level3">
<h3>Prediction with Decision Trees</h3>
<p><a href=http://blog.revolutionanalytics.com/2013/06/plotting-classification-and-regression-trees-with-plotrpart.html>Create decision tree</a></p>
<p>Instead of plotting a decision tree, we can quickly look at a graph of the cross-validation results, and see that the error rate is higher than the random forest method.</p>
<pre class="r"><code>set.seed(4726)
modelFitB1 &lt;- rpart(classe ~., method=&quot;class&quot;, data=train)
plot(modelFitB1)
text(modelFitB1)</code></pre>
<p><img src="index_files/figure-html/decisionTree-1.png" /></p>
<pre class="r"><code>plotcp(modelFitB1)</code></pre>
<p><img src="index_files/figure-html/decisionTree-2.png" /></p>
<p>A quick look at the results on teh decision tree and we see the variables we’re looking for intermingled. The Random Forest has a 99.83% accuracy rate, a .17% out-of-sample error rate, so we’ll progress with this for our prediction set.</p>
</div>
<div id="predicting-our-results" class="section level3">
<h3>Predicting our results</h3>
<p>First, we’ll use the same cleaning methods as above:</p>
<pre class="r"><code>cleanFormat &lt;- colnames(train[,-58]) # classe column removal
pmlTest &lt;-pmlTest[cleanFormat]
dim(pmlTest)</code></pre>
<pre><code>## [1] 20 57</code></pre>
<p>And we’ll coerce the data into the same format:</p>
<pre class="r"><code>for (i in 1:length(pmlTest) ) {
    for(j in 1:length(train)) {
        if( length( grep(names(train[i]), names(pmlTest)[j]) ) == 1)  {
            class(pmlTest[j]) &lt;- class(train[i])
        }      
    }      
}

# To get the same class between pmlTest and train
pmlTest &lt;- rbind(train[2,-58], pmlTest) ## remove excess rows
pmlTest &lt;- pmlTest[-1,]</code></pre>
<p>Then we apply the prediction model to the data:</p>
<pre class="r"><code>predictionFinal &lt;-predict(modelFitA1, pmlTest, type=&quot;class&quot;)</code></pre>
<p>And our final results.</p>
<pre class="r"><code>predictionFinal</code></pre>
<pre><code>## 22  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 
##  B  A  B  A  A  E  D  B  A  A  B  C  B  A  E  E  A  B  B  B 
## Levels: A B C D E</code></pre>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
